markdown: kramdown
highlighter: rouge
kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  enable_coderay: false
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

#google_analytics_id: UA-XXXXXXXX-X

repository: https://github.com/fagstoff/it.vgs.no
edit_url_base: https://github.com/fagstoff/it.vgs.no/blob/master/
help_url: https://github.com/jekyll/jekyll-help

collections:
  docs:
    output: true

name: IT.VGS • Læremidler for informasjonsteknologifaget
description: Frie læremidler for informasjonsteknologifaget i videregående opplæring
#venter med å legge inn url til sidene skal rulles ut
#url: http://it.vgs.no
baseurl: /it2

gems:
  - jekyll-feed

timezone: Europe/Oslo
